services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 99wealth_api
    restart: unless-stopped
    tty: true
    # depends_on:
    #   - mysql
    # ports:
    #   - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - app-network


  #NGINX
  webserver:
    image: nginx:alpine
    container_name: 99wealth_webserver
    restart: unless-stopped
    tty: true
    depends_on:
      - app
    ports:
      - 8181:8181
    volumes:
      - ./:/var/www/html/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: 99wealth_timescaledb
    environment:
      POSTGRES_DB: 99wealth
      POSTGRES_USER: 99wealth
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - timescale_data:/var/lib/postgresql/data


  redis:
    image: redis:alpine
    container_name: 99wealth_redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:

volumes:
  timescale_data:
