services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 99wealth_api
    restart: unless-stopped
    tty: true
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=timescaledb
      - DB_PORT=5432
      - DB_DATABASE=${WEALTH_DB_DATABASE}
      - DB_USERNAME=${WEALTH_DB_USERNAME}
      - DB_PASSWORD=${WEALTH_DB_PASSWORD}
      - REDIS_PASSWORD=${WEALTH_REDIS_PASSWORD}
    depends_on:
      - timescaledb    
    volumes:
      - .:/var/www/html
    networks:
      - app-network


  #NGINX
  webserver:
    image: nginx:alpine
    container_name: 99wealth_webserver
    restart: unless-stopped
    tty: true
    depends_on:
      - app
    ports:
      - 8181:8181
    volumes:
      - ./:/var/www/html/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: 99wealth_timescaledb
    environment:
      POSTGRES_DB: 99wealth
      POSTGRES_USER: ${WEALTH_DB_USERNAME}
      POSTGRES_PASSWORD: ${WEALTH_DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - ${WEALTH_TIMESCALEDB_VOLUME}:/var/lib/postgresql/data


  redis:
    image: redis:alpine
    container_name: 99wealth_redis
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${WEALTH_REDIS_PASSWORD} 
    command: redis-server --requirepass ${WEALTH_REDIS_PASSWORD}
    volumes:
      - ${WEALTH_REDIS_VOLUME}:/data
    networks:
      - app-network

networks:
  app-network:

# volumes:
#   timescale_data:
